### ISSUE TITLE
Ask users to install pybind, a dependency in setup.py

### ISSUE THREAD

**Issue by gwtaylor** [uoguelph-mlrg/PROTAX-GPU#1]
Install fails for me in a clean conda virtual env. I think the issue is `pybind11`, imported from `setup.py` is not a standard module.

I think a solution is to, before asking users to `pip install .`, have them  `pip install pybind11`.

Steps to reproduce:

Set up a minimal environment that lets me use pip:

```bash
conda create -n protax-gpu
conda activate protax-gpu
conda install pip
Channels:
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/homebrew/Caskroom/miniforge/base/envs/protax-gpu

  added / updated specs:
    - pip


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libexpat-2.5.0             |       hb7217d7_1          62 KB  conda-forge
    pip-23.3.1                 |     pyhd8ed1ab_0         1.3 MB  conda-forge
    python-3.12.0              |h47c9636_0_cpython        12.7 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        14.1 MB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h93a5062_5
  ca-certificates    conda-forge/osx-arm64::ca-certificates-2023.7.22-hf0a4a13_0
  libexpat           conda-forge/osx-arm64::libexpat-2.5.0-hb7217d7_1
  libffi             conda-forge/osx-arm64::libffi-3.4.2-h3422bc3_5
  libsqlite          conda-forge/osx-arm64::libsqlite-3.44.0-h091b4b1_0
  libzlib            conda-forge/osx-arm64::libzlib-1.2.13-h53f4e23_5
  ncurses            conda-forge/osx-arm64::ncurses-6.4-h463b476_2
  openssl            conda-forge/osx-arm64::openssl-3.1.4-h0d3ecfb_0
  pip                conda-forge/noarch::pip-23.3.1-pyhd8ed1ab_0
  python             conda-forge/osx-arm64::python-3.12.0-h47c9636_0_cpython
  readline           conda-forge/osx-arm64::readline-8.2-h92ec313_1
  setuptools         conda-forge/noarch::setuptools-68.2.2-pyhd8ed1ab_0
  tk                 conda-forge/osx-arm64::tk-8.6.13-h5083fa2_1
  tzdata             conda-forge/noarch::tzdata-2023c-h71feb2d_0
  wheel              conda-forge/noarch::wheel-0.41.3-pyhd8ed1ab_0
  xz                 conda-forge/osx-arm64::xz-5.2.6-h57fd34a_0


Proceed ([y]/n)? y


Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

Then using `pip` to set up PROTAX-GPU as per the instructions:

```bash
pip install . --dry-run
Processing /Users/gwtaylor/src/PROTAX-GPU
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/gwtaylor/src/PROTAX-GPU/setup.py", line 3, in <module>
          import pybind11
      ModuleNotFoundError: No module named 'pybind11'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by rvosa** [comment]
This is good to know. Please add this to the README in the root.
