### ISSUE TITLE
Built wheels but cannot run test_topk.py

### ISSUE THREAD

**Issue by gwtaylor** [uoguelph-mlrg/PROTAX-GPU#2]
I managed to successfully run `pip install .` on the Vector cluster.
I had to load the following modules:

```bash
module load cuda-11.8
module load cmake-3.20.2
```

Everything looks ok with the build:

```bash
(protax-gpu) gwtaylor@vremote:~/projects/PROTAX-GPU$ pip install .
Processing /fs01/home/gwtaylor/projects/PROTAX-GPU
  Preparing metadata (setup.py) ... done
Collecting jax (from protax==0.0.0)
  Using cached jax-0.4.20-py3-none-any.whl.metadata (23 kB)
Collecting jaxlib (from protax==0.0.0)
  Using cached jaxlib-0.4.20-cp312-cp312-manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting ml-dtypes>=0.2.0 (from jax->protax==0.0.0)
  Using cached ml_dtypes-0.3.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting numpy>=1.22 (from jax->protax==0.0.0)
  Using cached numpy-1.26.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting opt-einsum (from jax->protax==0.0.0)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting scipy>=1.9 (from jax->protax==0.0.0)
  Using cached scipy-1.11.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Using cached jax-0.4.20-py3-none-any.whl (1.7 MB)
Using cached jaxlib-0.4.20-cp312-cp312-manylinux2014_x86_64.whl (85.8 MB)
Using cached ml_dtypes-0.3.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (206 kB)
Using cached numpy-1.26.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.9 MB)
Using cached scipy-1.11.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (35.7 MB)
Building wheels for collected packages: protax
  Building wheel for protax (setup.py) ... done
  Created wheel for protax: filename=protax-0.0.0-cp312-cp312-linux_x86_64.whl size=245470 sha256=61bdacce10791e3c01b6fdd7334105d06dfb10e0a291de164688ed81ef1c40cd
  Stored in directory: /fs01/home/gwtaylor/.cache/pip/wheels/0c/4b/d6/2f499fbbe6e47b399e46aefdc71c53eaf716124c300e6f79f4
Successfully built protax
Installing collected packages: numpy, scipy, opt-einsum, ml-dtypes, jaxlib, jax, protax
Successfully installed jax-0.4.20 jaxlib-0.4.20 ml-dtypes-0.3.1 numpy-1.26.1 opt-einsum-3.3.0 protax-0.0.0 scipy-1.11.3
```

However, when I try to run `test_topk.py` from either PROTAX-GPU root or from `test/` it can't import `protax`:

```bash
(protax-gpu) gwtaylor@vremote:~/projects/PROTAX-GPU$ python tests/test_topk.py
Traceback (most recent call last):
  File "/fs01/home/gwtaylor/projects/PROTAX-GPU/tests/test_topk.py", line 5, in <module>
    from protax.taxonomy import CSRWrapper
ModuleNotFoundError: No module named 'protax'
(protax-gpu) gwtaylor@vremote:~/projects/PROTAX-GPU$ cd tests
(protax-gpu) gwtaylor@vremote:~/projects/PROTAX-GPU/tests$ python test_topk.py
Traceback (most recent call last):
  File "/fs01/home/gwtaylor/projects/PROTAX-GPU/tests/test_topk.py", line 5, in <module>
    from protax.taxonomy import CSRWrapper
ModuleNotFoundError: No module named 'protax'
```

I can import `protax` from PROTAX-GPU root but I cannot call `from protax.taxonomy import CSRWrapper` that is in `test_topk.py`. 

```bash
(protax-gpu) gwtaylor@vremote:~/projects/PROTAX-GPU$ python
Python 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:22) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import protax
>>>
```

```bash
Python 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:22) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from protax.taxonomy import CSRWrapper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/fs01/home/gwtaylor/projects/PROTAX-GPU/protax/taxonomy.py", line 1, in <module>
    import chex
ModuleNotFoundError: No module named 'chex'
```

I think the missing `chex` dependency is a separate issue. I think there may be something weird going on with how the `protax` package is installed.

**Comment by Cleanliness** [comment]
Issue seems to be fixed now after reorganizing project structure. Problem resulted from a circular dependency inside `knn_jax`

**Comment by gwtaylor** [comment]
Yes, I confirm this gets me through this error.

There are still some missing dependencies but I brought those over to #3.
